### ISSUE TITLE
how do i get this to work

### ISSUE THREAD

**Issue by Razkanaz** [DarkTrick/htmlfilemerger#7]
it keeps leaving this error
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ python3 -m pip install .
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Razkanaz** [comment]
i managed to install it
but now i can't merge the files

**Comment by DarkTrick** [comment]
Thank you for reporting!

I'll need some time to look into this (1~2 weeks). I guess there is a problem with the code (meaning, you don't need to try any more)

As a workaround for the moment I suggest not to install it, but use it without installation; See [*run without installation*](https://github.com/DarkTrick/htmlfilemerger#run-without-installation)

**Comment by Razkanaz** [comment]
no, i think the code is perfectly fine, i just don't know how to use it

**Comment by Razkanaz** [comment]
i tried opening powershell in the folder, and it said syntax error
i tried in the folder with the HTML

but none of them work, i think i'm just a bit dumb
can you provide more details on how to use the program?

**Comment by Razkanaz** [comment]
thanks for making this btw, if i get it to work, it would help so much

**Comment by Razkanaz** [comment]
ok, i think i got it to work
here are the instructions for those that want to use it and are having problems:
1. unzip the file and put it somewhere you can see it, like the documents folder
2. put the files inside the "SRC" folder, then go back to the main folder
3. right-click while holding shift, then click "open powershell"
4. type this into the powershell
"cd ./src
python htmlmerger [file name].html"
and then you should be able to do it

**Comment by Razkanaz** [comment]
P.S make sure to write python and not python3

**Comment by DarkTrick** [comment]
I'm glad it worked! 👍️

Thank you very much for the instructions! Can you help me refine them, so I can put them into the readme file.

I don't have Windows to test. Can you tell me if the following works?

 1. Download zip file from github
 2. Unzip the file into the folder `htmlmerger` and put it somewhere you can see it, like the documents folder
 3. Press and hold shift, then right-click the new `htmlmerger` folder (release shift now)
 4. Select "open powershell"
 5. Inside the powershell, write `python ./src/htmlmerger ` (don't forget the space at the end, **don't** press enter)<br>Depending on your system, you might need to write `python3` instead of `python`
 7. Drag and drop the html file you'd like to merge into the powershell. The full path of the file should appear after.
 8. Press enter.

**Comment by Razkanaz** [comment]
no. 5 is slightly innaccurate
you put the files inside the src folder (or alternatively type the full path to the file)
and then paste in (important, paste it in, don't type it)

cd ./src
python htmlmerger [put file name here, or write full path, example C:\Users\[username]\coding\Stopwatch.html]

and then press enter

**Comment by Razkanaz** [comment]
yes, that is exactly right, the instructions look very good and readable

except, instead of writing "python ./src/htmlmerger" you paste in

cd ./src
python htmlmerger

it is very important you paste it in, and not write it

**Comment by Razkanaz** [comment]
also, it does work, let me try to refine the instructions a bit
